"""Updating delivery table

Revision ID: 1692bbb616ce
Revises: ed238a7ffd2d
Create Date: 2024-08-29 16:17:45.750446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1692bbb616ce'
down_revision: Union[str, None] = 'ed238a7ffd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
