"""Add delivery location table

Revision ID: 919a22caac46
Revises: 3214e77359f7
Create Date: 2024-08-29 12:28:03.077961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919a22caac46'
down_revision: Union[str, None] = '3214e77359f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('suite', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('delivery_zone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_locations_business_type'), 'delivery_locations', ['business_type'], unique=False)
    op.create_index(op.f('ix_delivery_locations_city'), 'delivery_locations', ['city'], unique=False)
    op.create_index(op.f('ix_delivery_locations_delivery_zone'), 'delivery_locations', ['delivery_zone'], unique=False)
    op.create_index(op.f('ix_delivery_locations_id'), 'delivery_locations', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_locations_name'), 'delivery_locations', ['name'], unique=False)
    op.create_index(op.f('ix_delivery_locations_postal_code'), 'delivery_locations', ['postal_code'], unique=False)
    op.create_index(op.f('ix_delivery_locations_state'), 'delivery_locations', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_locations_state'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_postal_code'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_name'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_id'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_delivery_zone'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_city'), table_name='delivery_locations')
    op.drop_index(op.f('ix_delivery_locations_business_type'), table_name='delivery_locations')
    op.drop_table('delivery_locations')
    # ### end Alembic commands ###
