"""Updating tables for FK relations

Revision ID: ed238a7ffd2d
Revises: aafd31571bf6
Create Date: 2024-08-29 15:40:54.891200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed238a7ffd2d'
down_revision: Union[str, None] = 'aafd31571bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('quantity_scheduled', sa.Integer(), nullable=False))
    op.add_column('deliveries', sa.Column('delivery_status', sa.String(), nullable=False))
    op.add_column('deliveries', sa.Column('quantity_delivered', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('delivery_notes', sa.String(), nullable=True))
    op.drop_column('deliveries', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('deliveries', 'delivery_notes')
    op.drop_column('deliveries', 'quantity_delivered')
    op.drop_column('deliveries', 'delivery_status')
    op.drop_column('deliveries', 'quantity_scheduled')
    # ### end Alembic commands ###
