"""Updating delivery_locations table

Revision ID: f96e20e28078
Revises: 1692bbb616ce
Create Date: 2024-08-30 12:41:27.295791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96e20e28078'
down_revision: Union[str, None] = '1692bbb616ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_locations', sa.Column('place_id', sa.String(), nullable=True))
    op.add_column('delivery_locations', sa.Column('website', sa.String(), nullable=True))
    op.drop_column('delivery_locations', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_locations', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('delivery_locations', 'website')
    op.drop_column('delivery_locations', 'place_id')
    # ### end Alembic commands ###
